### ISSUE TITLE
cocosCreator的加速无效

### ISSUE THREAD

**Issue by android-1995** [rise-worlds/android_inject#1]
测试了一下CocosCreator的游戏hook gettimeofday和clock_gettime没有加速的效果，hook cocos_normal_update也一样没有加速效果

**Comment by rise-worlds** [comment]
cocosCreator需要hook webview相关的计时器，暂时未实现

**Comment by android-1995** [comment]
cocosCreator js相关的加速找到这个：https://forum.cocos.org/t/cocoscreator/98819
不知道hook so的话有没有什么hook点

**Comment by rise-worlds** [comment]
> cocosCreator js相关的加速找到这个：https://forum.cocos.org/t/cocoscreator/98819 不知道hook so的话有没有什么hook点

cocosCreator是在webview内运行的，我觉得一种可靠的方法是：hook页面加载相关的函数，在页面加载完成后再加载一段自己的js来覆盖对应的函数。
可能需要还原压缩或加密过的js代码，可能还需要针对不同cc的版本来处理。

**Comment by android-1995** [comment]
> > cocosCreator js相关的加速找到这个：https://forum.cocos.org/t/cocoscreator/98819 不知道hook so的话有没有什么hook点
> 
> cocosCreator是在webview内运行的，我觉得一种可靠的方法是：hook页面加载相关的函数，在页面加载完成后再加载一段自己的js来覆盖对应的函数。 可能需要还原压缩或加密过的js代码，可能还需要针对不同cc的版本来处理。

这样的话，可就太复杂😤

**Comment by android-1995** [comment]
https://docs.cocos.com/creator/3.8/manual/zh/advanced-topics/jsb-manual-binding.html 大佬，这个可以提供思路吗？

**Comment by android-1995** [comment]
找到了2.x版本和3.x版本的java调用js的方法。
3.x：
https://github.com/cocos/cocos-engine/blob/v3.8.4/native/cocos/platform/android/java/src/com/cocos/lib/JsbBridge.java
2.x：
https://github.com/cocos/engine-native/blob/v2.4.15/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxJavascriptJavaBridge.java

**Comment by android-1995** [comment]
找到方法：
```
伪代码：
org.cocos2dx.lib.Cocos2dxHelper.runOnGLThread(new Runnable() {
                @Override
                public void run() {
                   org.cocos2dx.lib.Cocos2dxJavascriptJavaBridge.evalString("cc.director.getScheduler().setTimeScale(" + speed + ");"); 
                }
            });
```
